-- ============================================================================
-- CM TECHMAP - AI Measurements Runtime Tables
-- Adds tables for terrain/building metrology generated by automatic AI pipeline.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS postgis;

-- ============================================================================
-- 1. Measurement Runs
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.ai_measurement_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    flight_asset_id UUID,
    flight_id UUID,
    orthomosaic_file_key VARCHAR(1000),
    dsm_file_key VARCHAR(1000),
    status VARCHAR(30) NOT NULL DEFAULT 'running',
    model_version VARCHAR(120) NOT NULL DEFAULT 'building_extractor_v1',
    terrain_model_version VARCHAR(120) NOT NULL DEFAULT 'terrain_extractor_v1',
    qa_score DOUBLE PRECISION,
    terrain_area_total_sqm DOUBLE PRECISION DEFAULT 0,
    built_area_total_sqm DOUBLE PRECISION DEFAULT 0,
    total_buildings INTEGER DEFAULT 0,
    total_terrain_patches INTEGER DEFAULT 0,
    error_message TEXT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_ai_measurement_runs_project_id ON public.ai_measurement_runs(project_id);
CREATE INDEX IF NOT EXISTS ix_ai_measurement_runs_status ON public.ai_measurement_runs(status);
CREATE INDEX IF NOT EXISTS ix_ai_measurement_runs_started_at ON public.ai_measurement_runs(started_at DESC);

-- ============================================================================
-- 2. Building Measurements
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.ai_building_measurements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id UUID NOT NULL REFERENCES public.ai_measurement_runs(id) ON DELETE CASCADE,
    detection_id UUID REFERENCES public.ai_detections(id) ON DELETE SET NULL,
    confidence DOUBLE PRECISION NOT NULL DEFAULT 0,
    area_sqm DOUBLE PRECISION NOT NULL DEFAULT 0,
    perimeter_m DOUBLE PRECISION,
    height_m DOUBLE PRECISION,
    floors_estimate INTEGER,
    building_type VARCHAR(80),
    orientation_deg DOUBLE PRECISION,
    compactness DOUBLE PRECISION,
    quality_score DOUBLE PRECISION,
    properties JSONB DEFAULT '{}',
    polygon geometry(Polygon, 4326),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_ai_building_measurements_run_id ON public.ai_building_measurements(run_id);
CREATE INDEX IF NOT EXISTS ix_ai_building_measurements_detection_id ON public.ai_building_measurements(detection_id);
CREATE INDEX IF NOT EXISTS ix_ai_building_measurements_area ON public.ai_building_measurements(area_sqm);
CREATE INDEX IF NOT EXISTS ix_ai_building_measurements_polygon ON public.ai_building_measurements USING GIST(polygon);

-- ============================================================================
-- 3. Terrain Measurements
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.ai_terrain_measurements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id UUID NOT NULL REFERENCES public.ai_measurement_runs(id) ON DELETE CASCADE,
    confidence DOUBLE PRECISION NOT NULL DEFAULT 0,
    area_sqm DOUBLE PRECISION NOT NULL DEFAULT 0,
    perimeter_m DOUBLE PRECISION,
    compactness DOUBLE PRECISION,
    surface_type VARCHAR(80) DEFAULT 'terrain',
    properties JSONB DEFAULT '{}',
    polygon geometry(Polygon, 4326),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_ai_terrain_measurements_run_id ON public.ai_terrain_measurements(run_id);
CREATE INDEX IF NOT EXISTS ix_ai_terrain_measurements_area ON public.ai_terrain_measurements(area_sqm);
CREATE INDEX IF NOT EXISTS ix_ai_terrain_measurements_polygon ON public.ai_terrain_measurements USING GIST(polygon);

-- ============================================================================
-- 4. Trigger for updated_at
-- ============================================================================
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_proc WHERE proname = 'trigger_set_updated_at'
    ) THEN
        CREATE OR REPLACE FUNCTION public.trigger_set_updated_at()
        RETURNS TRIGGER AS $f$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $f$ LANGUAGE plpgsql;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'set_updated_at_ai_measurement_runs'
    ) THEN
        CREATE TRIGGER set_updated_at_ai_measurement_runs
        BEFORE UPDATE ON public.ai_measurement_runs
        FOR EACH ROW EXECUTE FUNCTION public.trigger_set_updated_at();
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'set_updated_at_ai_building_measurements'
    ) THEN
        CREATE TRIGGER set_updated_at_ai_building_measurements
        BEFORE UPDATE ON public.ai_building_measurements
        FOR EACH ROW EXECUTE FUNCTION public.trigger_set_updated_at();
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'set_updated_at_ai_terrain_measurements'
    ) THEN
        CREATE TRIGGER set_updated_at_ai_terrain_measurements
        BEFORE UPDATE ON public.ai_terrain_measurements
        FOR EACH ROW EXECUTE FUNCTION public.trigger_set_updated_at();
    END IF;
END;
$$;

SELECT 'AI measurement runtime tables created' AS result;
