"""
CM TECHMAP — DSM Normalizer & Offset Extraction

This module handles the critical transformation of raw photogrammetric DSM/DTM
outputs from NodeODM into web-ready elevation data. Based on the engineering
principles documented in the research transcript:

  1. NORMALIZATION: Raw DSM from NodeODM contains absolute elevations
     (e.g., 800m+ for areas in Minas Gerais). The frontend terrain renderer
     needs relative heights (0-N meters above ground). We compute the
     Normalized DSM (nDSM = DSM - DTM) when DTM is available, or subtract
     the minimum elevation as a fallback.

  2. OFFSET EXTRACTION: OBJ files from photogrammetry are NOT georeferenced.
     The offset.xyz file contains the Float64 barycentric translation vector
     that maps local-origin coordinates back to global geodetic position.
     This is CRITICAL for preventing Z-jittering in WebGL/Three.js/MapLibre
     via the RTE (Relative-To-Eye) rendering technique.

  3. STATISTICS: Elevation statistics (min, max, mean, percentiles) are
     essential for the frontend to configure terrain exaggeration, building
     height extraction, and color ramp calibration.

References:
  - maps-research-transcript.md, Cap. 5 (offset.xyz / Z-jittering)
  - maps-research-transcript.md, Cap. 4 (RTE / Float64 → Float32 bridge)
"""

import logging
import os
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any

import numpy as np

logger = logging.getLogger(__name__)


# ══════════════════════════════════════════════════════════════════════════════
# Data Structures
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class OffsetXYZ:
    """
    Barycentric translation vector for georeferencing local-origin models.

    In the context of the research transcript (Cap. 5), this is the
    vec{T} = [T_x, T_y, T_z] that translates local-coordinate meshes
    back to global geodetic position:

        P_global = P_local + T

    The offset is stored in Float64 precision to prevent Z-jittering.
    The frontend JavaScript V8 engine uses Float64 natively, so this
    vector can be used directly for RTE calculations.
    """
    x: float = 0.0       # Easting or Longitude (Float64)
    y: float = 0.0       # Northing or Latitude (Float64)
    z: float = 0.0       # Elevation in meters (Float64)
    crs: str = "EPSG:4326"
    epsg: int = 4326

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def to_file(self, path: str | Path) -> None:
        """Write offset to a standard offset.xyz text file."""
        with open(path, "w") as f:
            f.write(f"{self.x:.10f} {self.y:.10f} {self.z:.6f}\n")
            f.write(f"# CRS: {self.crs}\n")
            f.write(f"# EPSG: {self.epsg}\n")
            f.write(f"# Generated by CM TECHMAP DSM Normalizer\n")
        logger.info(f"[OFFSET] Written to {path}: ({self.x}, {self.y}, {self.z})")

    @classmethod
    def from_file(cls, path: str | Path) -> "OffsetXYZ":
        """Read offset from a standard offset.xyz text file."""
        with open(path, "r") as f:
            line = f.readline().strip()
            parts = line.split()
            x, y, z = float(parts[0]), float(parts[1]), float(parts[2])

        crs = "EPSG:4326"
        epsg = 4326
        # Try to read CRS from comment lines
        with open(path, "r") as f:
            for raw_line in f:
                if "EPSG:" in raw_line and raw_line.startswith("#"):
                    try:
                        epsg_str = raw_line.split("EPSG:")[1].strip()
                        epsg = int(epsg_str)
                        crs = f"EPSG:{epsg}"
                    except (ValueError, IndexError):
                        pass

        return cls(x=x, y=y, z=z, crs=crs, epsg=epsg)


@dataclass
class ElevationStatistics:
    """Comprehensive elevation statistics for a DSM/nDSM raster."""
    min_m: float = 0.0
    max_m: float = 0.0
    mean_m: float = 0.0
    std_m: float = 0.0
    range_m: float = 0.0
    p5: float = 0.0
    p25: float = 0.0
    p50: float = 0.0     # median
    p75: float = 0.0
    p95: float = 0.0
    valid_pixels: int = 0
    nodata_pixels: int = 0
    total_pixels: int = 0
    is_normalized: bool = False

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class NormalizedDSMResult:
    """Result of DSM normalization with all extracted metadata."""
    normalized_path: str = ""
    offset: OffsetXYZ = field(default_factory=OffsetXYZ)
    statistics: ElevationStatistics = field(default_factory=ElevationStatistics)
    method: str = ""      # "ndsm" | "min_subtraction" | "raw"
    original_crs: str = ""
    original_epsg: int = 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "normalized_path": self.normalized_path,
            "offset": self.offset.to_dict(),
            "statistics": self.statistics.to_dict(),
            "method": self.method,
            "original_crs": self.original_crs,
            "original_epsg": self.original_epsg,
        }


# ══════════════════════════════════════════════════════════════════════════════
# Core Functions
# ══════════════════════════════════════════════════════════════════════════════

def normalize_dsm(
    dsm_path: str | Path,
    dtm_path: str | Path | None = None,
    output_path: str | Path | None = None,
    max_height_clamp: float = 200.0,
    smoothing_sigma: float = 0.0,
) -> NormalizedDSMResult:
    """
    Normalize a raw photogrammetric DSM for web rendering.

    This is the critical transformation that makes NodeODM elevation data
    usable in the frontend. Raw DSMs contain absolute elevations (e.g.,
    800m above sea level for Minas Gerais), but the terrain renderer
    needs relative heights (meters above ground level).

    Strategy:
      1. When DTM is available → nDSM = DSM - DTM (best accuracy)
      2. When DTM is absent → Subtract minimum elevation (fallback)

    Both methods produce a raster where:
      - Ground level ≈ 0 meters
      - Building roofs ≈ 3-30 meters
      - Trees ≈ 2-15 meters
      - Negative values clamped to 0
      - Values above max_height_clamp clamped

    Args:
        dsm_path: Path to the raw DSM GeoTIFF from NodeODM
        dtm_path: Optional DTM for precise nDSM computation
        output_path: Path for the normalized DSM output
        max_height_clamp: Maximum height value (clamp above this)
        smoothing_sigma: Gaussian smoothing sigma (0 = no smoothing)

    Returns:
        NormalizedDSMResult with path, offset, and statistics
    """
    try:
        import rasterio
        from rasterio.transform import array_bounds
    except ImportError:
        raise ImportError("rasterio is required for DSM normalization")

    dsm_path = Path(dsm_path)
    if output_path is None:
        output_path = dsm_path.parent / f"{dsm_path.stem}_normalized{dsm_path.suffix}"
    output_path = Path(output_path)

    logger.info(f"[DSM-NORM] Normalizing DSM: {dsm_path.name}")

    # ── Read DSM ──────────────────────────────────────────────────────────
    with rasterio.open(dsm_path) as src:
        dsm_data = src.read(1).astype(np.float64)
        dsm_profile = src.profile.copy()
        dsm_nodata = src.nodata
        dsm_crs = src.crs
        dsm_transform = src.transform
        dsm_bounds = src.bounds

    # Create validity mask
    if dsm_nodata is not None:
        valid_mask = ~np.isclose(dsm_data, dsm_nodata) & np.isfinite(dsm_data)
    else:
        valid_mask = np.isfinite(dsm_data)

    valid_data = dsm_data[valid_mask]

    if len(valid_data) == 0:
        logger.error("[DSM-NORM] No valid elevation data found in DSM")
        raise ValueError("DSM contains no valid elevation data")

    # ── Compute nDSM or subtract minimum ──────────────────────────────────
    method = "raw"

    if dtm_path and Path(dtm_path).exists():
        # Method 1: nDSM = DSM - DTM (most accurate)
        logger.info("[DSM-NORM] Computing nDSM (DSM - DTM)...")
        method = "ndsm"

        with rasterio.open(dtm_path) as dtm_src:
            dtm_data = dtm_src.read(1).astype(np.float64)
            dtm_nodata = dtm_src.nodata

        # Ensure matching dimensions
        if dtm_data.shape != dsm_data.shape:
            logger.warning(
                f"[DSM-NORM] DSM shape {dsm_data.shape} != DTM shape {dtm_data.shape}. "
                "Resampling DTM to match DSM."
            )
            from rasterio.warp import reproject, Resampling
            dtm_resampled = np.empty_like(dsm_data)
            with rasterio.open(dtm_path) as dtm_src:
                reproject(
                    source=dtm_src.read(1),
                    destination=dtm_resampled,
                    src_transform=dtm_src.transform,
                    src_crs=dtm_src.crs,
                    dst_transform=dsm_transform,
                    dst_crs=dsm_crs,
                    resampling=Resampling.bilinear,
                )
            dtm_data = dtm_resampled

        # DTM valid mask
        if dtm_nodata is not None:
            dtm_valid = ~np.isclose(dtm_data, dtm_nodata) & np.isfinite(dtm_data)
        else:
            dtm_valid = np.isfinite(dtm_data)

        combined_mask = valid_mask & dtm_valid

        # Compute nDSM
        normalized = np.zeros_like(dsm_data)
        normalized[combined_mask] = dsm_data[combined_mask] - dtm_data[combined_mask]

        # Store the DTM minimum as the base elevation for offset
        base_elevation = float(np.nanmin(dtm_data[dtm_valid])) if np.any(dtm_valid) else 0.0

        valid_mask = combined_mask
        logger.info(
            f"[DSM-NORM] nDSM computed. DTM base: {base_elevation:.2f}m, "
            f"nDSM range: [{np.nanmin(normalized[valid_mask]):.2f}, "
            f"{np.nanmax(normalized[valid_mask]):.2f}]m"
        )
    else:
        # Method 2: Subtract minimum elevation
        logger.info("[DSM-NORM] No DTM available. Subtracting minimum elevation...")
        method = "min_subtraction"

        min_elev = float(np.nanmin(valid_data))
        base_elevation = min_elev
        normalized = dsm_data - min_elev

        logger.info(
            f"[DSM-NORM] Subtracted base elevation: {min_elev:.2f}m. "
            f"Normalized range: [0, {float(np.nanmax(valid_data)) - min_elev:.2f}]m"
        )

    # ── Clamp values ──────────────────────────────────────────────────────
    normalized[~valid_mask] = 0.0
    normalized = np.clip(normalized, 0.0, max_height_clamp)

    # ── Optional smoothing ────────────────────────────────────────────────
    if smoothing_sigma > 0:
        from scipy.ndimage import gaussian_filter
        normalized = gaussian_filter(normalized, sigma=smoothing_sigma)
        logger.info(f"[DSM-NORM] Applied Gaussian smoothing (σ={smoothing_sigma})")

    # ── Write normalized DSM ──────────────────────────────────────────────
    write_profile = dsm_profile.copy()
    write_profile.update(
        dtype="float32",
        count=1,
        nodata=0.0,
        compress="deflate",
        predictor=2,
        tiled=True,
        blockxsize=256,
        blockysize=256,
    )

    with rasterio.open(output_path, "w", **write_profile) as dst:
        dst.write(normalized.astype(np.float32), 1)

    logger.info(f"[DSM-NORM] Written normalized DSM: {output_path.name}")

    # ── Extract offset ────────────────────────────────────────────────────
    offset = extract_offset_metadata(dsm_path)

    # ── Compute statistics ────────────────────────────────────────────────
    stats = compute_elevation_statistics(
        output_path, is_normalized=True
    )

    return NormalizedDSMResult(
        normalized_path=str(output_path),
        offset=offset,
        statistics=stats,
        method=method,
        original_crs=str(dsm_crs) if dsm_crs else "EPSG:4326",
        original_epsg=dsm_crs.to_epsg() if dsm_crs and dsm_crs.to_epsg() else 4326,
    )


def extract_offset_metadata(raster_path: str | Path) -> OffsetXYZ:
    """
    Extract the barycentric offset vector from a georeferenced raster.

    This implements the concept from the research transcript (Cap. 5, Int. 4):
    The offset.xyz file contains the Float64 translation vector that maps
    local-origin (0,0,0) coordinates to global geodetic coordinates.

    For WebGL rendering:
      - The frontend loads models in local coordinates (small Float32 values)
      - The offset vector is applied via RTE (Relative-To-Eye) in the CPU
        using JavaScript's native Float64 arithmetic
      - This prevents Z-jittering by keeping GPU calculations in Float32-safe range

    The offset is computed as the centroid of the raster's geographic extent,
    with the mean elevation as the Z component.

    Args:
        raster_path: Path to a georeferenced raster (DSM, orthomosaic, etc.)

    Returns:
        OffsetXYZ with Float64 centroid coordinates
    """
    try:
        import rasterio
        from rasterio.warp import transform_bounds
    except ImportError:
        raise ImportError("rasterio is required for offset extraction")

    raster_path = Path(raster_path)

    with rasterio.open(raster_path) as src:
        bounds = src.bounds
        data = src.read(1).astype(np.float64)
        crs = src.crs
        nodata = src.nodata

    # Get valid elevation data for Z offset
    if nodata is not None:
        valid = data[~np.isclose(data, nodata) & np.isfinite(data)]
    else:
        valid = data[np.isfinite(data)]

    mean_elevation = float(np.nanmean(valid)) if len(valid) > 0 else 0.0

    # Calculate centroid in the raster's native CRS
    center_x = (bounds.left + bounds.right) / 2.0
    center_y = (bounds.bottom + bounds.top) / 2.0

    epsg = crs.to_epsg() if crs and crs.to_epsg() else 4326
    crs_str = f"EPSG:{epsg}"

    # If CRS is projected (UTM, etc.), also compute WGS84 coordinates
    if crs and epsg != 4326:
        try:
            wgs84_bounds = transform_bounds(crs, "EPSG:4326", *bounds)
            lon = (wgs84_bounds[0] + wgs84_bounds[2]) / 2.0
            lat = (wgs84_bounds[1] + wgs84_bounds[3]) / 2.0
            logger.info(
                f"[OFFSET] Projected CRS {crs_str} centroid: "
                f"({center_x:.6f}, {center_y:.6f}) → "
                f"WGS84: ({lon:.8f}, {lat:.8f})"
            )
            # Store WGS84 for frontend compatibility
            offset = OffsetXYZ(
                x=lon, y=lat, z=mean_elevation,
                crs="EPSG:4326", epsg=4326,
            )
        except Exception as e:
            logger.warning(f"[OFFSET] CRS transform failed: {e}. Using native CRS.")
            offset = OffsetXYZ(
                x=center_x, y=center_y, z=mean_elevation,
                crs=crs_str, epsg=epsg,
            )
    else:
        offset = OffsetXYZ(
            x=center_x, y=center_y, z=mean_elevation,
            crs=crs_str, epsg=epsg,
        )

    logger.info(
        f"[OFFSET] Extracted from {raster_path.name}: "
        f"({offset.x:.8f}, {offset.y:.8f}, {offset.z:.2f}) [{offset.crs}]"
    )
    return offset


def compute_elevation_statistics(
    raster_path: str | Path,
    is_normalized: bool = False,
) -> ElevationStatistics:
    """
    Compute comprehensive elevation statistics from a DSM/nDSM raster.

    These statistics are used by the frontend for:
    - Terrain exaggeration calibration
    - Building height threshold tuning
    - Color ramp configuration for elevation visualization
    - Quality assessment of photogrammetric outputs

    Args:
        raster_path: Path to the elevation raster
        is_normalized: Whether the raster has been normalized (heights above ground)

    Returns:
        ElevationStatistics with full percentile distribution
    """
    try:
        import rasterio
    except ImportError:
        raise ImportError("rasterio is required for elevation statistics")

    raster_path = Path(raster_path)

    with rasterio.open(raster_path) as src:
        data = src.read(1).astype(np.float64)
        nodata = src.nodata

    # Build valid data mask
    if nodata is not None:
        valid_mask = ~np.isclose(data, nodata) & np.isfinite(data)
    else:
        valid_mask = np.isfinite(data)

    valid = data[valid_mask]
    total_pixels = int(data.size)
    valid_count = int(len(valid))
    nodata_count = total_pixels - valid_count

    if valid_count == 0:
        logger.warning(f"[ELEV-STATS] No valid data in {raster_path.name}")
        return ElevationStatistics(
            total_pixels=total_pixels,
            nodata_pixels=nodata_count,
            is_normalized=is_normalized,
        )

    # Compute percentiles in one call (efficient)
    percentiles = np.percentile(valid, [5, 25, 50, 75, 95])

    stats = ElevationStatistics(
        min_m=float(np.nanmin(valid)),
        max_m=float(np.nanmax(valid)),
        mean_m=float(np.nanmean(valid)),
        std_m=float(np.nanstd(valid)),
        range_m=float(np.nanmax(valid) - np.nanmin(valid)),
        p5=float(percentiles[0]),
        p25=float(percentiles[1]),
        p50=float(percentiles[2]),
        p75=float(percentiles[3]),
        p95=float(percentiles[4]),
        valid_pixels=valid_count,
        nodata_pixels=nodata_count,
        total_pixels=total_pixels,
        is_normalized=is_normalized,
    )

    logger.info(
        f"[ELEV-STATS] {raster_path.name}: "
        f"range=[{stats.min_m:.2f}, {stats.max_m:.2f}]m, "
        f"mean={stats.mean_m:.2f}m, std={stats.std_m:.2f}m, "
        f"pixels={stats.valid_pixels}/{stats.total_pixels} valid"
    )
    return stats


def parse_offset_file(offset_path: str | Path) -> OffsetXYZ:
    """
    Parse an offset.xyz file generated by photogrammetry software.

    Compatible with the format produced by PIX4D, ODM, and other SfM tools:
      Line 1: X Y Z (space-separated Float64 values)
      Lines 2+: Optional comments (# prefixed)

    This is the format described in the research transcript (Cap. 5):
      "If you open this file in notepad, at the top should be the shift
       amount to x/y/z."

    Args:
        offset_path: Path to the offset.xyz file

    Returns:
        OffsetXYZ with parsed coordinates
    """
    return OffsetXYZ.from_file(offset_path)
